FROM resin/%%RESIN_MACHINE_NAME%%-debian

ENV INITSYSTEM on
ENV PATH "$PATH:/root/.cargo/bin"

RUN apt-get -q update && apt-get install -yq --no-install-recommends \
	build-essential curl file \
	&& apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src/app

RUN curl https://sh.rustup.rs -sSf | sh -s -- --no-modify-path -y

COPY . /usr/src/app

RUN cargo build

CMD ./target/debug/resin-rust-hello-world
